spring:
  profiles:
    active: '${SPRING_PROFILES_ACTIVE}'
  servlet:
    multipart:
      enabled: true
      max-file-size: '1GB'
      max-request-size: '1GB'

# SERVER CONFIG
server:
  port: '${PORT:8080}'
  error:
    whitelabel:
      enabled: false
#  servlet:
#    context-path: '/api'

