# SERVER CONFIG
server:
  error:
    include-message: always

# SPRING DATA JPA CONFIG
spring:
  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}'
    username: '${DB_USER}'
    password: '${DB_PASSWORD}'
  jpa:
    show-sql: true
    properties:
      ddl-auto: none
  sql:
    init:
      mode: always